#spring.application.name=KeyCloakTestProject
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myapp_realm
server:
  port: 9092

logging:
  level:
    org.springframework.web: DEBUG


spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: myapp
            client-secret: RtFNsfFHAG67zjUlCH0vqOnYQdd2dwvh
            scope: openid, profile, email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/myapp_realm
            user-name-attribute: preferred_username

keycloak:
  server-url: http://localhost:8082/
  realm: myapp_realm
  username: root
  password: rootroot

